name: My first workflow
on: [push, workflow_dispatch]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    env:
      USER: "Ubuntu"
    steps:
      - run: echo ${{env.USER}}
      - run: echo $USER
