name: My first workflow
on: [push, workflow_dispatch]
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    env:
      USER: "Ubuntu"
    steps:
      - run: echo ${{secrets.AWS_SECRET}}
      - run: echo ${{vars.DIR_PATH}}
      - run: echo $USER
